// <auto-generated />
using System;
using ImobAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImobAPI.Migrations
{
    [DbContext(typeof(ImobContext))]
    [Migration("20260402182003_BuildDbSeeded")]
    partial class BuildDbSeeded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImobAPI.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<string>("CodBanco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpfCnpj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrgaoExpedidor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoClienteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.HasIndex("TipoClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ImobAPI.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApoliceSegFianca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<int?>("Contratante1Id")
                        .HasColumnType("int");

                    b.Property<int?>("Contratante2Id")
                        .HasColumnType("int");

                    b.Property<int?>("Contratante3Id")
                        .HasColumnType("int");

                    b.Property<int?>("Contratante4Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFimVigencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInicioVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FiadorId")
                        .HasColumnType("int");

                    b.Property<int?>("ImovelId")
                        .HasColumnType("int");

                    b.Property<int?>("ModalidadeContratoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ObjetoContratoId")
                        .HasColumnType("int");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("int");

                    b.Property<string>("PropostaSegFianca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<int>("Vencimento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.HasIndex("Contratante1Id");

                    b.HasIndex("Contratante2Id");

                    b.HasIndex("Contratante3Id");

                    b.HasIndex("Contratante4Id");

                    b.HasIndex("FiadorId");

                    b.HasIndex("ImovelId");

                    b.HasIndex("ModalidadeContratoId");

                    b.HasIndex("ObjetoContratoId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TipoContratoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("ImobAPI.Entities.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Bin")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoFotoId")
                        .HasColumnType("int");

                    b.Property<int?>("VistoriaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.HasIndex("ImovelId");

                    b.HasIndex("TipoFotoId");

                    b.HasIndex("VistoriaId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ImobAPI.Entities.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<string>("Cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Condominio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Foro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InscricaoIptu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntencaoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Iptu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Metragem")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCbmerj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxaIncendio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoImovelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.HasIndex("IntencaoId");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TipoImovelId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("ImobAPI.Entities.Intencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("Intencoes");
                });

            modelBuilder.Entity("ImobAPI.Entities.ModalidadeContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("ModalidadesContrato");
                });

            modelBuilder.Entity("ImobAPI.Entities.ObjetoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("ObjetosContrato");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("TiposCliente");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("TiposContrato");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("TiposFoto");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.ToTable("TiposImovel");
                });

            modelBuilder.Entity("ImobAPI.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ImobAPI.Entities.Vistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("CadastradorId")
                        .HasColumnType("int");

                    b.Property<int?>("ContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataEntregaChaves")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVistoria")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ImovelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CadastradorId");

                    b.HasIndex("ContratoId");

                    b.HasIndex("ImovelId");

                    b.ToTable("Vistorias");
                });

            modelBuilder.Entity("ImobAPI.Entities.Cliente", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.HasOne("ImobAPI.Entities.TipoCliente", "TipoCliente")
                        .WithMany()
                        .HasForeignKey("TipoClienteId");

                    b.Navigation("Cadastrador");

                    b.Navigation("TipoCliente");
                });

            modelBuilder.Entity("ImobAPI.Entities.Contrato", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.HasOne("ImobAPI.Entities.Cliente", "Contratante1")
                        .WithMany()
                        .HasForeignKey("Contratante1Id");

                    b.HasOne("ImobAPI.Entities.Cliente", "Contratante2")
                        .WithMany()
                        .HasForeignKey("Contratante2Id");

                    b.HasOne("ImobAPI.Entities.Cliente", "Contratante3")
                        .WithMany()
                        .HasForeignKey("Contratante3Id");

                    b.HasOne("ImobAPI.Entities.Cliente", "Contratante4")
                        .WithMany()
                        .HasForeignKey("Contratante4Id");

                    b.HasOne("ImobAPI.Entities.Cliente", "Fiador")
                        .WithMany()
                        .HasForeignKey("FiadorId");

                    b.HasOne("ImobAPI.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId");

                    b.HasOne("ImobAPI.Entities.ModalidadeContrato", "ModalidadeContrato")
                        .WithMany()
                        .HasForeignKey("ModalidadeContratoId");

                    b.HasOne("ImobAPI.Entities.ObjetoContrato", "ObjetoContrato")
                        .WithMany()
                        .HasForeignKey("ObjetoContratoId");

                    b.HasOne("ImobAPI.Entities.Cliente", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId");

                    b.HasOne("ImobAPI.Entities.TipoContrato", "TipoContrato")
                        .WithMany()
                        .HasForeignKey("TipoContratoId");

                    b.Navigation("Cadastrador");

                    b.Navigation("Contratante1");

                    b.Navigation("Contratante2");

                    b.Navigation("Contratante3");

                    b.Navigation("Contratante4");

                    b.Navigation("Fiador");

                    b.Navigation("Imovel");

                    b.Navigation("ModalidadeContrato");

                    b.Navigation("ObjetoContrato");

                    b.Navigation("Proprietario");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("ImobAPI.Entities.Foto", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.HasOne("ImobAPI.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId");

                    b.HasOne("ImobAPI.Entities.TipoFoto", "TipoFoto")
                        .WithMany()
                        .HasForeignKey("TipoFotoId");

                    b.HasOne("ImobAPI.Entities.Vistoria", "Vistoria")
                        .WithMany()
                        .HasForeignKey("VistoriaId");

                    b.Navigation("Cadastrador");

                    b.Navigation("Imovel");

                    b.Navigation("TipoFoto");

                    b.Navigation("Vistoria");
                });

            modelBuilder.Entity("ImobAPI.Entities.Imovel", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.HasOne("ImobAPI.Entities.Intencao", "Intencao")
                        .WithMany()
                        .HasForeignKey("IntencaoId");

                    b.HasOne("ImobAPI.Entities.Cliente", "Proprietario")
                        .WithMany()
                        .HasForeignKey("ProprietarioId");

                    b.HasOne("ImobAPI.Entities.TipoImovel", "TipoImovel")
                        .WithMany()
                        .HasForeignKey("TipoImovelId");

                    b.Navigation("Cadastrador");

                    b.Navigation("Intencao");

                    b.Navigation("Proprietario");

                    b.Navigation("TipoImovel");
                });

            modelBuilder.Entity("ImobAPI.Entities.Intencao", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.ModalidadeContrato", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.ObjetoContrato", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoCliente", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoContrato", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoFoto", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.TipoImovel", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.Navigation("Cadastrador");
                });

            modelBuilder.Entity("ImobAPI.Entities.Vistoria", b =>
                {
                    b.HasOne("ImobAPI.Entities.Usuario", "Cadastrador")
                        .WithMany()
                        .HasForeignKey("CadastradorId");

                    b.HasOne("ImobAPI.Entities.Contrato", "Contrato")
                        .WithMany()
                        .HasForeignKey("ContratoId");

                    b.HasOne("ImobAPI.Entities.Imovel", "Imovel")
                        .WithMany()
                        .HasForeignKey("ImovelId");

                    b.Navigation("Cadastrador");

                    b.Navigation("Contrato");

                    b.Navigation("Imovel");
                });
#pragma warning restore 612, 618
        }
    }
}
